### Get all users
POST http://localhost:8000/users
Content-Type: application/json

{
  "firstName": "Joh",
  "lastName": "Dojj",
  "email": "galib@gmail.com",
  "password": "your_password_Here",
  "ddd":"virus"
}