### Get all users
POST http://localhost:8000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyMiwiZW1haWwiOiJqb2huQGdkb2UuY29tIiwiaWF0IjoxNzI5ODc1NTYwLCJleHAiOjE3Mjk4NzkxNjAsImF1ZCI6ImxvY2FsaG9zdDo4MDAwIiwiaXNzIjoibG9jYWxob3N0OjgwMDAifQ.wTcrnVy3W7v2T6NsR5_RxSYZko-E3SSEi_d31Uo8usk

{
  "users" :[
  {
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@gdoxzczxdde.com",
  "password": "12345678@Galib"
  },
  {
  "firstName": "John",
  "lastName": "Doe", 
  "email": "john@gdoddxcve.com",
  "password": "12345678@Galib"
  },
  {
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@gdxcvodde.com",
  "password": "12345678@Galib"
  },
  {
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@gdxcvxodde.com",
  "password": "12345678@Galib"
  }
]
}