### Get all users
POST http://localhost:8000/users
Content-Type: application/json

{
  "firstName": "Asadullah",
  "lastName": "Al Galib",
  "email": "galib@gmail.com",
  "password": "12345678@Galib"
}